### ISSUE TITLE
Spectral norm out of domain

### ISSUE THREAD

**Issue by tb6g16** [The-ReSolver/Fields.jl#10]
While trying to debug the residual gradient, I've found an instance where the dot product of a spectral array with itself is negative (should always be non-negative).

I believe the issue to be a result of the quadrature weights used in the LinearAlgebra.dot() method, as these are the only negative parts of the expression being evaluated.

https://github.com/The-ReSolver/Fields.jl/blob/82afdc3baed8282ffb53b4876d8d190d705d55a2/src/spectralfield.jl#L28-L48

@gasagna, correct me if I'm wrong, but I was under the impression all the weights produced by the quadweights functions should be non-negative?

https://github.com/The-ReSolver/Fields.jl/blob/82afdc3baed8282ffb53b4876d8d190d705d55a2/src/quadweights.jl#L6-L25

I have inspected the weights produced the small tests performed in "test_quadweights.jl" and there is a case where there is a non-negative weight, shown below.

https://github.com/The-ReSolver/Fields.jl/blob/82afdc3baed8282ffb53b4876d8d190d705d55a2/test/test_quadweights.jl#L15-L16

**Comment by gasagna** [comment]
I believe this can happen if the `order` argument in `quadweights` is too large. That code is fitting polynomials to chunks of grid points, so when you have too many it might produce rubbish. For a Chebychev grid you should be using different formulae to get the weight.

**Comment by tb6g16** [comment]
Created a new method for calculating weights for a Chebyshev grid using the already computed Chebyshev differentiation matrix. Using this the problem seems to have resolved itself.

https://github.com/The-ReSolver/ChebUtils.jl/blob/3a90971703052921eb35426b83803ae9f03dde1a/src/ChebUtils.jl#L87
